import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// IMPORT YOUR PROVIDER HERE
// Adjust the path based on where you saved the Toast component
import { ToastProvider } from "./context/ToastContext";

const geist = Geist({ subsets: ["latin"] });
const geistMono = Geist_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.className} ${geistMono.className}`}>
        {/* Wrap your children with the Provider */}
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
 